POST http://localhost:4000/register
Content-Type: application/json

{
  "password": "password"
}

# RESPONSE BODY:
# {
#   "success":false,
#   "message":"Invalid request.\nMust contain username and password."
# }


POST http://localhost:4000/register
Content-Type: application/json

{
  "username": "testAccount1"
}

# RESPONSE BODY:
# {
#   "success":false,
#   "message":"Invalid request.\nMust contain username and password."
# }


POST http://localhost:4000/register
Content-Type: application/json

{
  "username": "testAccount1",
  "password": "password"
}

#  RESPONSE BODY:
# {
#   "success":true,
#   "message":"Registration successful.",
#   "credential_id":1
# }


POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "testAccount1",
  "password": "password"
}

# RESPONSE BODY:
# {
#   "success":true,
#   "message":"Login Successful. Welcome testAccount1",
#   "session":{
#     "session_id":1,
#     "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiY3JlZGVudGlhbHMiLCJ1c2VyX2lkIjpudWxsLCJ1c2VybmFtZSI6InRlc3RBY2NvdW50MSIsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTU2ODU5NjkwNiwiZXhwIjoxNTY4NjAwNTA2fQ.Zsc48KnPSkxzf4YG3R7MCzcIG-WKTqDsVc1Cgsq-6AE",
#     "isValid":1
#   }
# }


POST http://localhost:4000/verify
Content-Type: application/json

{
  "session":{
    "session_id":1,
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiY3JlZGVudGlhbHMiLCJ1c2VyX2lkIjpudWxsLCJ1c2VybmFtZSI6InRlc3RBY2NvdW50MSIsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTU2ODU5NjkwNiwiZXhwIjoxNTY4NjAwNTA2fQ.Zsc48KnPSkxzf4YG3R7MCzcIG-WKTqDsVc1Cgsq-6AE",
    "isValid":1
  }
}

# RESPONSE BODY:
# {
#   "success": true,
#   "message": "Session is still valid."
# }


POST http://localhost:4000/logout
Content-Type: application/json

{
  "session":{
    "session_id":1,
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiY3JlZGVudGlhbHMiLCJ1c2VyX2lkIjpudWxsLCJ1c2VybmFtZSI6InRlc3RBY2NvdW50MSIsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTU2ODU5NjkwNiwiZXhwIjoxNTY4NjAwNTA2fQ.Zsc48KnPSkxzf4YG3R7MCzcIG-WKTqDsVc1Cgsq-6AE",
    "isValid":1
  }
}

# RESPONSE BODY:
# {
#   "success": true,
#   "message": "Successfully logged out."
# }


POST http://localhost:4000/verify
Content-Type: application/json

{
  "session":{
    "session_id":1,
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiY3JlZGVudGlhbHMiLCJ1c2VyX2lkIjpudWxsLCJ1c2VybmFtZSI6InRlc3RBY2NvdW50MSIsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTU2ODU5NjkwNiwiZXhwIjoxNTY4NjAwNTA2fQ.Zsc48KnPSkxzf4YG3R7MCzcIG-WKTqDsVc1Cgsq-6AE",
    "isValid":1
  }
}

# RESPONSE BODY:
# {
#   "success": false,
#   "message": "Session is no longer valid."
# }